# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  workflow_call:
    inputs:
      registry-name:
        default: eclipse-lmos
        type: string
        required: false
    secrets:
      oss-username:
        required: true
      oss-password:
        required: true
      signing-key-id:
        required: true
      signing-key:
        required: true
      signing-key-password:
        required: true
      registry-username:
        required: false
      registry-password:
        required: false

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.commits[0].message, 'Release:') != true && github.actor != 'eclipse-lmos-bot'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5.0.0
      - name: Set up JDK 25
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
      - name: Build and publish with Gradle
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.oss-username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.oss-password }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.signing-key-id }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing-key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing-key-password }}
          REGISTRY_URL: ghcr.io
          REGISTRY_USERNAME: ${{ secrets.registry-username }}
          REGISTRY_PASSWORD: ${{ secrets.registry-password }}
          REGISTRY_NAMESPACE: ${{ inputs.registry-name }}
        run: |
          ./gradlew publish
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
