# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  workflow_call:
    inputs:
      registry-name:
        default: eclipse-lmos
        type: string
        required: false
    secrets:
      oss-username:
        required: true
      oss-password:
        required: true
      signing-key-id:
        required: true
      signing-key:
        required: true
      signing-key-password:
        required: true
      registry-username:
        required: false
      registry-password:
        required: false

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0
      - name: Build and publish with Gradle
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.oss-username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.oss-password }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.signing-key-id }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing-key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing-key-password }}
          REGISTRY_URL: ghcr.io
          REGISTRY_USERNAME: ${{ secrets.registry-username }}
          REGISTRY_PASSWORD: ${{ secrets.registry-password }}
          REGISTRY_NAMESPACE: ${{ inputs.registry-name }}
        run: |
          ./gradlew publish
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.3.0
