# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Release Milestone

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-M[1-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-RC[1-9]+'

jobs:
  build-and-release-milestone:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: eclipse-lmos/lmos-router
          path: lmos-router
      - run: scripts/prepeareRelease.sh '${{ github.ref_name }}' lmos-router
      #- name: "Create tags"
      #  env:
      #    GH_TOKEN: ${{ github.token }}
      #  run: gh release create '${{ github.ref_name }}'
      #- name: "Create release info"
      #  env:
      #    GH_TOKEN: ${{ github.token }}
      #  run: gh release create '${{ github.ref_name }}' --generate-notes --prerelease
