# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      release-type:
        default: "Milestone"
        required: true
        type: string
      registry-name:
        default: eclipse-lmos
        type: string
        required: false
    secrets:
      oss-username:
        required: true
      oss-password:
        required: true
      signing-key-id:
        required: true
      signing-key:
        required: true
      signing-key-password:
        required: true
      bot-token:
        required: true
      registry-username:
        required: false
      registry-password:
        required: false
    outputs:
      version:
       value: ${{ jobs.build-and-release.outputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: ${{ steps.Publish.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          token: ${{ secrets.bot-token }}
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.oss-username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.oss-password }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.signing-key-id }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing-key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing-key-password }}
          REGISTRY_URL: ghcr.io
          REGISTRY_USERNAME: ${{ secrets.registry-username }}
          REGISTRY_PASSWORD: ${{ secrets.registry-password }}
          REGISTRY_NAMESPACE: ${{ inputs.registry-name }}
          GH_TOKEN: ${{ secrets.bot-token }}
        run: |
          version=1.2.3
          echo "version=${version}" >> $GITHUB_OUTPUT
