# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      release-type:
        default: "Milestone"
        required: true
        type: string
      registry-name:
        default: eclipse-lmos
        type: string
        required: false
    secrets:
      oss-username:
        required: true
      oss-password:
        required: true
      signing-key-id:
        required: true
      signing-key:
        required: true
      signing-key-password:
        required: true
      bot-token:
        required: true
      registry-username:
        required: false
      registry-password:
        required: false
    outputs:
      version:
       value: ${{ jobs.buildAndRelease.outputs.version }}

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.Publish.outputs.version }}
    steps:
      - name: Publish
        run: |
          version=1.2.3
          echo "version=${version}" >> $GITHUB_OUTPUT
