# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      release-type:
        default: "Milestone"
        required: true
        type: string
      registry-name:
        default: eclipse-lmos
        type: string
        required: false
    secrets:
      oss-username:
        required: true
      oss-password:
        required: true
      signing-key-id:
        required: true
      signing-key:
        required: true
      signing-key-password:
        required: true
      bot-token:
        required: true
      registry-username:
        required: false
      registry-password:
        required: false
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.build-and-release.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.build-and-release.outputs.output2 }}

jobs:
  build-and-release:
    name: Generate output
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
